# AUTOGENERATED! DO NOT EDIT! File to edit: ../app.ipynb.

# %% auto 0
__all__ = ['learn', 'image', 'label', 'examples', 'intf', 'get_float_labels', 'predict_image']

# %% ../app.ipynb 2
from fastai.vision.all import *
import gradio as gr

def get_float_labels(path):
    return float(path.name.split('_')[0])

# %% ../app.ipynb 4
learn = load_learner("model_w_lr.pkl")

# %% ../app.ipynb 5
def predict_image(img):
    pred, _, _ = learn.predict(img)
    return int(pred[0])

# %% ../app.ipynb 8
image = gr.Image(shape=(200, 200))
label = gr.Label()
examples = ['10.jpg', '50.jpg', '100.jpg']

intf = gr.Interface(fn=predict_image, inputs=image, outputs=label, examples=examples)
intf.launch(inline=False)
